Create wmj_PR_test.txt
Yao-class-cpp-studio/battle_game pull request #11
Opened 2023-01-03 11:21 UTC by wmj2022

2023-01-11 05:54 UTC, wmj2022 commented
![01102b6a79c9e9354d2143862aa4c77](https://user-images.githubusercontent.com/113516461/211728319-3f3ebdcc-af9f-4a34-944e-ed3df5947061.png)
![gold](https://user-images.githubusercontent.com/113516461/211728175-bd86af89-daf4-46e0-b6b5-385c9d30c9c8.png)
![0f3de98e86fe1eff16a082006d15350](https://user-images.githubusercontent.com/113516461/211728279-67df3d4f-4430-44ce-874c-0e7053860993.png)
![347a3a81092906a259f83cd5bbcc041](https://user-images.githubusercontent.com/113516461/211728381-bb5bb824-f20f-4583-b07b-e01291056c1b.png)

2023-01-11 15:07 UTC, LazyJazz requested changes

2023-01-11 15:07 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/wmj_tank.cpp" "units/wmj_tank.h" "bullets/gold_bullet.h" "bullets/DF11A_rocket.cpp"  "bullets/laser.h" "bullets/laser.cpp")
undo this.

2023-01-11 15:07 UTC, LazyJazz commented on src/battle_game/core/bullets/laser.h
> +class laser : public Bullet {
Class name should be in CamelCase

2023-01-11 15:07 UTC, LazyJazz commented on src/battle_game/core/bullets/gold_bullet.h
> +class gold_bullet : public Bullet {
CamelCase

2023-01-11 15:07 UTC, LazyJazz commented on src/battle_game/core/bullets/DF11A_rocket.h
> +class DF11A_rocket : public Bullet {
CamelCase

2023-01-11 15:07 UTC, LazyJazz commented on src/battle_game/core/units/wmj_tank.h
> +class wmj_Tank : public Unit {
CamelCase

2023-01-11 15:07 UTC, LazyJazz commented on src/battle_game/core/units/wmj_tank.cpp
> +}
Inherit from unit::Tank if you are using the very same function

2023-01-12 13:50 UTC, LazyJazz requested changes

2023-01-12 13:50 UTC, LazyJazz commented on CMakeSettings.json
> +}
delete this file

2023-01-12 13:50 UTC, LazyJazz commented on src/battle_game/core/bullets/DF11A_rocket.cpp
> +dfRocket::dfRocket(GameCore *core,
DFRocket

2023-01-12 13:50 UTC, LazyJazz commented on src/battle_game/core/bullets/gold_bullet.h
> +class goldBullet : public Bullet {
GoldBullet

2023-01-12 13:50 UTC, LazyJazz commented on wmj_PR_test.txt
> +PR test only
Delete this file

2023-01-12 14:27 UTC, LazyJazz approved these changes
LGTM!

2023-01-15 10:43 UTC, closed without merging