[New Unit] Round UFO
Yao-class-cpp-studio/battle_game pull request #122
Opened 2023-01-07 09:00 UTC by Fireond

Add round UFO unit.
Use mouse and w/s to move, better move experience. 
Shoot round distributed bullets.

2023-01-07 15:35 UTC, LazyJazz requested changes

2023-01-07 15:35 UTC, LazyJazz commented on src/battle_game/core/units/round_UFO.cpp
> +}
This is a fake change, please inherit from unit::Tank if you are reusing the very same function.
Tell me the difference if there is one.

2023-01-07 15:35 UTC, LazyJazz commented on src/battle_game/core/units/round_UFO.cpp
> +}
As you have changed the model, this function should be changed as well.

2023-01-07 15:35 UTC, LazyJazz commented on src/battle_game/core/units/round_UFO.cpp
> +}
What is the purpose of this?

2023-01-08 08:16 UTC, Fireond commented on src/battle_game/core/units/round_UFO.cpp
> +}
变成了用ws前进后退鼠标控制旋转，没有使用ad

2023-01-09 11:22 UTC, LazyJazz submitted a review, later dismissed
LGTM! Call me in wechat if you want to merge your contribution into the main branch.

2023-01-10 15:24 UTC, LazyJazz approved these changes
LGTM!

2023-01-10 15:26 UTC, merged