Create READMEEEE
Yao-class-cpp-studio/battle_game pull request #123
Opened 2023-01-07 09:46 UTC by QhtIsNotAvailable

2023-01-07 11:12 UTC, sshockwave commented
虽然可以随意改动，但是创建无意义文件对项目是有影响的。把这个文件删掉就可以了。

2023-01-09 11:24 UTC, LazyJazz requested changes
LGTM! Just some nits.

2023-01-09 11:24 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +add_library(${lib_name} units/Split_bullet_cannon.cpp units/Split_bullet_cannon.h bullets/split_bullet.cpp bullets/split_bullet.h)
Pls undo this.

2023-01-09 11:24 UTC, LazyJazz commented on src/battle_game/core/selectable_units.cpp
> +  ADD_SELECTABLE_UNIT(unit::TNL);
These are not necessary

2023-01-15 05:54 UTC, QhtIsNotAvailable commented
激光坦克Laser Tank提供了大部分代码，由我，刘家瑜，张开心共同完成；collision tank仅提供了思路，后被邀请做测试，可以不算在我做的issue内

2023-01-15 10:45 UTC, QhtIsNotAvailable commented
Split bullet tank: 发射一个长子弹，一段时间后分裂成5个小子弹；长子弹本身伤害和小子弹一样

Laser tank: 按住鼠标发射以鼠标为中轴的六束细激光并缓慢向中心旋转聚拢成为一束粗激光，粗激光伤害是六束小激光之和
激光可穿透任意多敌人但不能穿透障碍物和墙
按E后按住鼠标发出至多（2077-2000）帧加强后的粗激光，打满的伤害可以秒掉一辆满血坦克，cd20秒。

贡献：
张开心--设计激光和激光坦克的原型（激光的颜色可随机变换）
钱海天--用给定激光的模型制作激光武器的分束，颜色，透明度和聚拢效果
刘家瑜--制作大招

2023-01-15 16:33 UTC, qinchuanhui requested changes

2023-01-15 16:33 UTC, qinchuanhui commented on src/battle_game/core/README.md
> +    你可以通过这个指针调用游戏核心的相应功能函数。
Lots of meaningless changes, plz fix them. (perhaps just use the current main-repo README.md here)

2023-01-15 16:33 UTC, qinchuanhui commented on src/battle_game/core/bullets/laser.h
> +  glm::vec4 color_{};
Naming issue, more understandable and `UpdateColor` for functions, `combo_time_` for private variables

2023-01-15 16:33 UTC, qinchuanhui commented on src/battle_game/core/bullets/split_bullet.h
> +        int split_countdown;
Naming issue,  class name: `SplitBullet` and private variables naming

2023-01-15 16:33 UTC, qinchuanhui commented on src/battle_game/core/units/tiny_tank.cpp
> +  std::cout << player_id_ << std::endl;
Why write this? do u use it to debug? Maybe delete it.

2023-01-15 16:33 UTC, qinchuanhui commented on src/battle_game/core/units/Laser_Tank.cpp
> +}
If use all same functions, u should inherit the class `Tank`

2023-01-16 14:04 UTC, qinchuanhui approved these changes
OK, you can get the corresponding score

2023-01-16 14:04 UTC, closed without merging