[Two Utilities, Modified, Want to be Reviewed]Hidden Treasure & Replicator
Yao-class-cpp-studio/battle_game pull request #131
Opened 2023-01-08 02:22 UTC by hwk22

关于Hidden Treasure：
修正了private variables的命名问题。
实现了#42中提到的Hidden Treasure功能。由于背景板较为拥挤，该功能的入口函数已被注释。如果要观察效果，可以去掉game_core.cpp函数SetScene第2~3行的注释，或直接参考视频：https://cloud.tsinghua.edu.cn/f/44e9f6faf7e9412bb35a/
代码的底层逻辑是寄生obstacle::block的unit。
一些说明：
（1）Treasure的血量是随机值。
（2）Treasure颜色和位置在库存中随机挑选，保证任何时刻背景板上都有两个Treasure。
（3）视频的后半部分检验了寄生obstacle的效果。可以看到Tank有一半插入。事实上这是obstacle的一个bug，tank也能插入位于(-3.0f, 4.0f)的真正obstacle。
（4）Treasure的主体仍为unit，为保证代码统一性，不另写奖励机制。

关于Replicator：
实现了#111提到的功能。同上一个任务，为避免干扰，该功能的入口函数被注释，在game_core.cpp函数SetScene第2~3行。或直接参考视频：https://cloud.tsinghua.edu.cn/f/2267500fd09d418e9f1b/
一些说明：
（1）Replicator被击中时，直观表现为颜色变亮，向六个方向发射一至二个子弹。
（2）同一个Replicator使用（被击中）一定次数后会自动消失，变为另一个位置的Replicator。
（3）Replicator的底层逻辑和Hidden Treasure相同，都是寄生obstacle的unit。由于本任务obstacle的尺寸应当小于正常的Block（直径为d的正六边形面积显然小于边长为d的正方形），在obstacles文件夹下创立新的类型：repli_block.cpp/h。
（4）保证任意两个Replicator不会互相击中，造成死循环。

2023-01-09 11:26 UTC, LazyJazz requested changes
Just a nit.

2023-01-09 11:26 UTC, LazyJazz commented on src/battle_game/core/units/hidden_treasure.h
> +  int type_id;
private variables should be in lower_case_ ending with an underscore

2023-01-11 04:31 UTC, hwk22 commented
> Just a nit.

Already modified.

2023-01-12 14:43 UTC, LazyJazz approved these changes
LGTM!

2023-01-15 08:55 UTC, closed without merging