[Debug] ThreeBodyMan
Yao-class-cpp-studio/battle_game pull request #133
Opened 2023-01-08 03:17 UTC by EDGE-qy

Bug mentioned in #95 fixed referring to #78 
[Skill] SafetyDeclare fit in the Skill Display Board in #78

2023-01-09 11:45 UTC, LazyJazz requested changes
LGTM! Just fix the nit.

2023-01-09 11:45 UTC, LazyJazz commented on src/battle_game/core/units/three_body_man.cpp
> +  SafetyDeclare.function = SKILL_ADD_FUNCTION(ThreeBodyMan::SafetyDeclareClick);
variable name should be in lower_case.

2023-01-09 13:22 UTC, EDGE-qy commented
> LGTM! Just fix the nit.

Fixed

2023-01-10 15:29 UTC, LazyJazz approved these changes
LGTM! Call me on wechat if you want to merge this pr into the main branch.

2023-01-15 08:55 UTC, closed without merging