test.cpp
Yao-class-cpp-studio/battle_game pull request #152
Opened 2023-01-08 15:01 UTC by TLLtangling

just a useless test

2023-01-12 14:48 UTC, LazyJazz requested changes

2023-01-12 14:48 UTC, LazyJazz commented on src/battle_game/core/game_core.h
> +  [[nodiscard]] glm::vec4 GetPlayerColorbooboo(uint32_t player_id) const;
What is this for? If this is not generally used, pls do this in your local codes. you can use GetRenderPerspective() to get the internal value render_perspective_

2023-01-12 14:48 UTC, LazyJazz commented on src/battle_game/core/units/boobootank.h
> +class boobootank : public Tank {
BigCamelCase

2023-01-12 14:48 UTC, LazyJazz commented on src/battle_game/core/units/boobootank.cpp
> +}
If you did not make changes to these functions, inherit from unit::Tank.

2023-01-12 14:48 UTC, LazyJazz commented on src/battle_game/core/bullets/booboobullet2.h
> +class booboobullet2 : public Bullet {
BigCamelCase

2023-01-12 14:48 UTC, LazyJazz commented on src/battle_game/core/bullets/booboobullet.h
> +class booboobullet : public Bullet {
BigCamelCase

2023-01-15 15:06 UTC, qinchuanhui requested changes

2023-01-15 15:06 UTC, qinchuanhui commented on src/battle_game/core/units/BoobooTank.cpp
> +}
You should not rewrite this function again.

2023-01-15 15:06 UTC, qinchuanhui commented on src/battle_game/core/units/BoobooTank.cpp
> +      turret_vertices.push_back(
Why rewrite this code, it seems to do the same thing as constructor-function of class `Tank`.
You can look at codes of other, if you don't know how to inherit the Tank class correctly.

2023-01-16 08:34 UTC, qinchuanhui approved these changes
OK, you can get the corresponding score

2023-01-16 08:35 UTC, closed without merging