issue1： skill accelerate and rageshoot
Yao-class-cpp-studio/battle_game pull request #163
Opened 2023-01-09 07:17 UTC by Wazrrr

在elementary tank中完成了技能acclerate（Q），使用后可以加速并获得三个强化子弹。
技能rageshoot（E），使用后可以将攻速变为原来两倍，在释放瞬间还会一次性射出很多很多子弹。

2023-01-09 12:14 UTC, LazyJazz commented
Merge this into your former PR.

2023-01-09 12:15 UTC, LazyJazz requested changes
One pr at a time

2023-01-12 14:54 UTC, LazyJazz requested changes

2023-01-12 14:54 UTC, LazyJazz commented on src/battle_game/core/bullet.h
> +  float CRIT_rate = 0.3;
lower_case_ ending with an underscore.

2023-01-16 10:56 UTC, qinchuanhui commented
Why no update? I will just close this PR.

2023-01-16 10:56 UTC, closed without merging