[Add Unit] Udongein, based on SpellCaster(scalable unit)
Yao-class-cpp-studio/battle_game pull request #206
Opened 2023-01-10 14:49 UTC by BAN-43-32532

This is an experimental unit Udongein (happy New Year of the Rabbit) which adopts a common way to move (WASD or Arrow keys instead of as a tank), and it support two skills (I would rather call it Spell). It is an extension from a more basic unit SpellCaster. I would continue working on it, and I need others' suggestions.

2023-01-10 15:56 UTC, LazyJazz requested changes
Good idea.

2023-01-10 15:56 UTC, LazyJazz commented on src/battle_game/core/units/spell_caster.h
> +};
Put these into new files

2023-01-11 09:52 UTC, BAN-43-32532 reviewed
I have made necessary changes, together with some utility updates.

2023-01-11 09:54 UTC, BAN-43-32532 commented
What should I do after completing these changes?

2023-01-12 15:07 UTC, LazyJazz submitted a review, later dismissed
LGTM!

2023-01-13 15:21 UTC, LazyJazz approved these changes
LGTM!

2023-01-13 15:21 UTC, merged