Adding new bullet called poisonous_bullet --closes issue #35
Yao-class-cpp-studio/battle_game pull request #208
Opened 2023-01-10 15:46 UTC by XiaoxiangRdM

实现issue #35 Utility : poisonous bullet 中的poisonous_bullet。
设定一次攻击扣除被打击对象的 40% 当前血量，之后血量向下取整
此外也可以手动调整poisonous_bullet.h中的三个参数，改变扣除血量的比率，当前血量/最大血量，血量向下/向上取整，以细调游戏平衡性。
实际使用时，使用GenerateBullet<bullet::PoisonousBullet>()即可。

贡献者：
严涵宇 Fireond，制作子弹图标，修改子弹图标相关代码，分析设计代码实现思路，实现poisonous_bullet.cpp部分内容
罗民睿XiaoxiangRdM，参照cannon_ball创建并实现poisonous_bullet.h，poisonous_bullet.cpp

2023-01-10 15:59 UTC, LazyJazz requested changes

2023-01-10 15:59 UTC, LazyJazz commented on src/battle_game/core/bullets/poisonous_bullet.h
> +  bool is_round_down{1}; // if 0: for health count round up when hitted
lower_case_ ending with an underscore

2023-01-11 02:28 UTC, XiaoxiangRdM commented
issues are fixed

2023-01-11 16:00 UTC, LazyJazz approved these changes
LGTM!

2023-01-13 03:02 UTC, XiaoxiangRdM commented
抱歉操作错误了，把主仓库的一些改动更新了进来，我提交的部分没有什么变化，没有再做改动

2023-01-13 15:23 UTC, LazyJazz approved these changes
LGTM!

2023-01-15 08:12 UTC, closed without merging