New unit (task 2)
Yao-class-cpp-studio/battle_game pull request #211
Opened 2023-01-11 02:44 UTC by RYQ-22

2023-01-12 15:12 UTC, LazyJazz requested changes
Fix the nits

2023-01-13 04:05 UTC, RYQ-22 commented
> Fix the nits
Has been modified.

2023-01-13 15:25 UTC, LazyJazz requested changes

2023-01-13 15:25 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/ryq_tank.cpp" "units/ryq_tank.h" "units/ryq_tank2.h" "units/ryq_tank2.cpp" "obstacles/brambles.h" "obstacles/brambles.cpp")
remove these

2023-01-14 06:32 UTC, RYQ-22 commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/ryq_tank.cpp" "units/ryq_tank.h" "units/ryq_tank2.h" "units/ryq_tank2.cpp" "obstacles/brambles.h" "obstacles/brambles.cpp")
Issues have been fixed.

2023-01-15 10:17 UTC, qinchuanhui approved these changes
LGTM, you can get the score.
But don't merge it directly due to the format error.

2023-01-15 10:17 UTC, qinchuanhui commented on src/battle_game/core/units/ryq_tank.h
> +  uint32_t fire1_count_num_{120};
Had better use `fire1_count_down_1_`. 
Well, just OK this time

2023-01-15 10:20 UTC, qinchuanhui requested changes

2023-01-15 10:20 UTC, qinchuanhui commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/ryq_tank.cpp" "units/ryq_tank.h" "units/ryq_tank2.h" "units/ryq_tank2.cpp")
Seems you didn't fix the Cmake issue

2023-01-15 10:21 UTC, qinchuanhui commented on src/battle_game/core/units/ryq_tank.h
> +  uint32_t fire1_count_num_{120};
Sry, you should first fix Cmake error and get the score

2023-01-15 10:30 UTC, RYQ-22 commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/ryq_tank.cpp" "units/ryq_tank.h" "units/ryq_tank2.h" "units/ryq_tank2.cpp")
Issues have been fixed.

2023-01-15 10:42 UTC, qinchuanhui approved these changes

2023-01-15 10:42 UTC, closed without merging