Invincible Time（want to be merged）
Yao-class-cpp-studio/battle_game pull request #215
Opened 2023-01-11 05:44 UTC by RYQ-22

为坦克出生时设置了3s的无敌时间
如图：
![Invincible Time](https://user-images.githubusercontent.com/113417175/211726935-323e3693-08a5-423d-a544-1d190a7848ee.jpg)

2023-01-11 05:45 UTC, RYQ-22 commented
无敌时间内血条为蓝色，支持所有unit

2023-01-12 15:17 UTC, LazyJazz requested changes

2023-01-12 15:17 UTC, LazyJazz commented on CMakeSettings.json
> +}
Delete this file, add it to .gitignore

2023-01-12 15:17 UTC, LazyJazz commented on README.md
> +（改动）
delete this

2023-01-12 15:17 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files}  )
why are u making this change?

2023-01-12 15:17 UTC, LazyJazz commented on src/battle_game/core/unit.h
> +  float invincibleTime{3 * 60};
lower_case_ ending with an underscore

2023-01-13 04:13 UTC, RYQ-22 commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files}  )
加文件时vs自动改的，没删干净（）

2023-01-13 05:46 UTC, RYQ-22 commented on CMakeSettings.json
> +}
已修改

2023-01-13 15:26 UTC, LazyJazz requested changes

2023-01-13 16:55 UTC, RYQ-22 commented on .gitignore
> +}
Issues are fixed.

2023-01-15 10:26 UTC, qinchuanhui approved these changes
You can get the score, but seems all of your PRs have some format ERROR (e.g.  in `gitignore` , `CMakeLists.txt`🤦‍♀️.

2023-01-15 10:28 UTC, closed without merging