score system version 1.0
Yao-class-cpp-studio/battle_game pull request #231
Opened 2023-01-12 03:38 UTC by jason-huang03

I add a score system. When you successfully shoot the enemy, you will get 5 points. When you shoot the obstacles, you will lose 5 points.

2023-01-12 15:25 UTC, LazyJazz requested changes

2023-01-12 15:25 UTC, LazyJazz commented on src/battle_game/core/game_core.h
> +  glm::vec2 get_boundary_low();
BigCamelCase

2023-01-12 15:25 UTC, LazyJazz commented on src/battle_game/core/unit.h
> +  int get_score();
BigCamelCase

2023-01-15 13:15 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score.

2023-01-15 13:15 UTC, closed without merging