[Utility]Neutral Turret
Yao-class-cpp-studio/battle_game pull request #232
Opened 2023-01-12 03:48 UTC by CoffeePot1206

finish #156

2023-01-12 04:47 UTC, CoffeePot1206 commented
[README.txt](https://github.com/Yao-class-cpp-studio/battle_game/files/10398269/README.txt)
Features, bugs are included in the README. (Why cannot I attach .md file...)

2023-01-12 15:26 UTC, LazyJazz requested changes

2023-01-12 15:26 UTC, LazyJazz commented on src/battle_game/core/units/neutral_turret.h
> +  glm::vec2 findEnermy();
BigCamelCase

2023-01-13 02:53 UTC, CoffeePot1206 commented
[README.txt](https://github.com/Yao-class-cpp-studio/battle_game/files/10407748/README.txt)

出生点的bug已经修复。

2023-01-13 15:30 UTC, LazyJazz approved these changes
LGTM!

2023-01-14 04:21 UTC, closed without merging