Better Simulation for Collision
Yao-class-cpp-studio/battle_game pull request #242
Opened 2023-01-12 09:31 UTC by jason-huang03

not done yet.

2023-01-12 15:31 UTC, LazyJazz requested changes

2023-01-12 15:31 UTC, LazyJazz commented on src/battle_game/core/game_core.cpp
> +void GameCore::handle_collision(glm::vec2 &p) {
BigCamelCase

2023-01-12 15:31 UTC, LazyJazz commented on src/battle_game/core/unit.h
> +  int get_score();
BigCamelCase

2023-01-16 15:16 UTC, qinchuanhui commented
plz fix ur bugs first

2023-01-17 02:17 UTC, closed without merging