[New Unit] Heal Tank & [New Bullet] Inhale Bullet（want to be merged）
Yao-class-cpp-studio/battle_game pull request #249
Opened 2023-01-12 12:45 UTC by jk21lcl

加入新单位：治疗坦克（heal tank）
特点：初始血量100，初始最大血量150，每0.8s回复1点血量，每15s在保持血量百分比不变的情况下将血量上限加10。
普通攻击方式：向前方40度范围内发射5颗伤害为6的子弹，攻击间隔1s。
E技能（inhale）：在5s内攻击间隔缩短至0.5s，向前方50度范围内发射9颗伤害为2的子弹，在这段时间内，每当有一颗子弹打中敌人时自身回复2点血量，技能冷却时间15s。
Q技能（refresh）：恢复至满血，冷却时间45s。

加入新子弹：吸血子弹（inhale bullet）
特点：打中敌方时可以让子弹发出者回复与子弹攻击力相同的血量

另：
1、在unit里加入成员函数AddAttackBuff，当子弹打到敌方时会调用这个函数，可以实现回血、经验值等功能。
2、在cannonball的update函数里，pusheventdealdamge函数的第二个参数貌似有问题，已修复
3、triple_shot_tank在第一次发射炮弹时只能发射一颗，bug已修复

此pr与 #176 相同，后者在merge的时候自动关了

2023-01-12 15:36 UTC, LazyJazz approved these changes
LGTM, but the in-progress code should be removed.

2023-01-12 15:36 UTC, LazyJazz commented on src/battle_game/core/game_core.cpp
> +      unit->AddAttackBuff();
What is this?

2023-01-12 15:51 UTC, jk21lcl commented on src/battle_game/core/game_core.cpp
> +      unit->AddAttackBuff();
已经移除AddAttackBuff函数

2023-01-13 12:04 UTC, jk21lcl commented
由于在 #275 里已经有人提出了更好的解决方案，因此在本pr内不对triple_shot_tank作出修改

2023-01-15 08:11 UTC, qinchuanhui requested changes

2023-01-15 08:11 UTC, qinchuanhui commented on src/battle_game/core/README.md
> +������Ԫ�صĻ���ͳһ�̳��Զ������ͣ�[Object](object.h)�������Ƕ���һ���ض���Ԥ�蹦�ܣ����ڷ�����ʵ���Լ����뷨��
Lots of meaningless changes in this file (maybe comes from formatter), just fix this, don't commit this changes

2023-01-16 11:31 UTC, closed without merging