Having completed two tasks all in tiny tank zcszcs522
Yao-class-cpp-studio/battle_game pull request #261
Opened 2023-01-13 01:47 UTC by zcszcs522

#136 Utility: Day/Night system
#136 老师对不起，我好像还没完全搞清楚如何申领这个issue并关闭之
在这个issue里，改了game_core的内容，但我经过测试应该只会影响我自己的单位，就是叫Tank_gx的class
#82  Blocks of Good Luck and Bad Luck
#82 这个issue是我自己提的，目前关了，但不知道是否算是申领了
这个issue同样也是加在了tank_gx里，目前会有血量超过100%的情况，这个问题想改过来并不困难，但我认为不改更接近提这个issue时的本意，因此我改了unit.cpp里RenderLifeBar这个函数，让血量超过100%时图形界面里的血条只显示100%的部分（掉血时也是），这个功能对于其他血量会超过100%的单位也同样适用

2023-01-13 15:36 UTC, LazyJazz requested changes

2023-01-13 15:36 UTC, LazyJazz commented on CMakeSettings.json
> +
Delete this file and add its filename into .gitignore.

2023-01-13 15:36 UTC, LazyJazz commented on src/battle_game/app/app.h
> +  //current_ = this;
delete this

2023-01-13 15:36 UTC, LazyJazz commented on src/battle_game/battle_game.cpp
> +  srand(static_cast<unsigned>(time(nullptr)));
why r u using srand? I gave you GameCore::RandomFloat and GameCore::RandomInt

2023-01-16 03:51 UTC, qinchuanhui requested changes
Your auto check failed, mainly because you add a submodule `battle_game`

2023-01-16 03:51 UTC, qinchuanhui commented on src/battle_game/core/units/tiny_tank_zcszcs522.h
> +class Tank_gx : public Unit {
Naming: `TankGx`

2023-01-16 09:35 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score

2023-01-16 09:36 UTC, closed without merging