Rocket Launcher& Drops [Hope to be merged]
Yao-class-cpp-studio/battle_game pull request #285
Opened 2023-01-13 12:05 UTC by YikaiZheng

之前的两个分支有些乱了，这个是我本地测试过最新的版本，希望能把前两个PR的内容merge进去。

2023-01-13 15:12 UTC, LazyJazz requested changes

2023-01-13 15:12 UTC, LazyJazz commented on src/battle_game/core/game_core.cpp
> +    float y = 20.0f * RandomFloat() - 10.0f;
Please use GameCore::boundary_low_ and GameCore::boundary_high_.

2023-01-13 15:16 UTC, LazyJazz commented
Please close your former PRs if you no longer need them

2023-01-16 11:35 UTC, qinchuanhui approved these changes
OK，you can get the corresponding score

2023-01-16 11:35 UTC, closed without merging