subtask 1
Yao-class-cpp-studio/battle_game pull request #3
Opened 2023-01-03 10:00 UTC by Megumi-X

2023-01-04 01:22 UTC, Megumi-X commented
加入我自己设计的tank_xxy，将坦克的模型改成了梯形可以分辨前后，窄的一边为前面，宽的一边为后面

2023-01-05 07:36 UTC, LazyJazz commented on CMakeSettings.json
> +}
Delete this

2023-01-05 07:37 UTC, LazyJazz requested changes

2023-01-05 07:37 UTC, LazyJazz commented on src/battle_game/core/units/tank_xxy.h
> +};
You can inherits from unit::Tank directly if you are noting applying any changes

2023-01-05 13:42 UTC, LazyJazz requested changes

2023-01-05 13:42 UTC, LazyJazz commented on src/battle_game/core/units/tank_xxy.cpp
> +}  // namespace
Remove those

2023-01-06 04:48 UTC, LazyJazz approved these changes
LGTM!

2023-01-06 04:49 UTC, merged