[Utility] Defence Tank
Yao-class-cpp-studio/battle_game pull request #311
Opened 2023-01-13 15:44 UTC by CoffeePot1206

新unit：Defence Tank

技能：
1. 按Q开启护盾，能防住敌人的子弹，同时自己也在掉血，一段时间后消失
2. 按E放置塔台，能攻击敌方目标，同时自己也在掉血，一段时间后消失

2023-01-13 15:58 UTC, LazyJazz requested changes

2023-01-13 15:58 UTC, LazyJazz commented on src/battle_game/core/units/neutral_turret.h
> +  bool setBlock_ = true;
lower_case_ ending with an underscore

2023-01-14 04:31 UTC, CoffeePot1206 commented on src/battle_game/core/units/neutral_turret.h
> +  bool setBlock_ = true;
Thx for reminding! Now fixed.

2023-01-16 04:18 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score

2023-01-16 04:18 UTC, closed without merging