New unit: Jinitaimei
Yao-class-cpp-studio/battle_game pull request #312
Opened 2023-01-13 15:46 UTC by Zixuan-Cao

New unit: Jinitaimei
- Jinitaimei can fire a basketball, which can rebound twice when it comes across obstacles.
- She can launtch a skill called TieShanKao, which enables her to fire basketballs without CD. 
    - This kind of basketball can rebound fifth,
    - but the damage of which will decline exponentially. 
Use Jinitaimei wisely! When enemies are far from her, her normal attack is powerful, while when enemies are close to her, her skill can even kill enemies in several frames. But be careful! Jinitaimei is under the threat of enemies' attacking range when approaching them.

2023-01-13 15:59 UTC, LazyJazz requested changes

2023-01-13 15:59 UTC, LazyJazz commented on src/battle_game/app/app.cpp
> +//test
delete this.

2023-01-13 15:59 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/jinitaimei.h" "units/jinitaimei.cpp"  "bullets/basketball.cpp" "bullets/basketball.h" "bullets/small_basketball.h" "bullets/small_basketball.
undo this.

2023-01-13 15:59 UTC, LazyJazz commented on src/battle_game/core/units/jinitaimei.cpp
> +}//mouse
inherit from unit::Tank

2023-01-16 12:27 UTC, Zixuan-Cao commented
solve some problems

2023-01-16 13:48 UTC, qinchuanhui requested changes

2023-01-16 13:48 UTC, qinchuanhui commented on src/battle_game/core/units/jinitaimei.cpp
> +
If u use the same functions of `Tank`, no need to rewrite

2023-01-16 13:48 UTC, qinchuanhui commented on src/battle_game/core/units/jinitaimei.cpp
> +}//mouse
If u use the same functions of `Tank`, no need to rewrite

2023-01-16 13:48 UTC, qinchuanhui commented on src/battle_game/core/units/jinitaimei.cpp
> +}
If u use the same functions of `Tank`, no need to rewrite

2023-01-16 14:40 UTC, qinchuanhui approved these changes
OK，u can get the corresponding score

2023-01-16 14:40 UTC, qinchuanhui commented on src/battle_game/core/units/jinitaimei.cpp
> +}
In fact, u don't even need to write this or define these functions in `.h` file , because the function can be inherited directly.

2023-01-16 14:42 UTC, closed without merging