peatanktest
Yao-class-cpp-studio/battle_game pull request #341
Opened 2023-01-14 08:58 UTC by zhouxs22

2023-01-14 14:47 UTC, qinchuanhui commented
Have you finish it or just a test?  Please add some description about your work.

2023-01-14 14:50 UTC, qinchuanhui commented on src/battle_game/app/app.cpp
> +// pull request test
Unrealeted file changes like this (or something in `fonts` folder), should not be included to commit and push.

2023-01-15 09:47 UTC, zhouxs22 commented
My works:
1 add pea_tank.cpp and pea_tank.h in src/battle_game/core/units which is designed to shoot in 4 directions simutaneously with each bullet dealing half damage
2 add speedbullet:(defined in src/battle_game/core/units) which is designed to increase its speed after some certain number of updates(my solution to issue#296)
These works are NOT TESTED.( I spent about half a week searching on Google/Stack Overflow and asking TAs/classmates/in the WeChat Group but still cannot get my Visual Studio generating battle.exe correctly, so I cannot do the test temporarily.I'll try to work on it in the remaining days but please grade it if I cannot get Visual Studio work before the deadline.)

2023-01-16 11:15 UTC, qinchuanhui commented
plz fix your bugs first

2023-01-16 11:53 UTC, zhouxs22 commented
> plz fix your bugs first

It seems they're fixed now. Sorry about that since my VSCode seemed to be not working well (and both me and TA & classmates & Google I sought for help couldn't really fix) and it may not build successfully even when there was no bugs at all (and GitHub ran the version of code successfully)

2023-01-16 15:03 UTC, qinchuanhui requested changes
Don't submit your `.obsidian` folder, just delete it from ur code-repo

2023-01-16 15:03 UTC, qinchuanhui commented on src/battle_game/core/bullets/speed_bullets.h
> +  float count;
naming: `count_`

2023-01-16 15:45 UTC, zhouxs22 commented
> Don't submit your `.obsidian` folder, just delete it from ur code-repo

'.obsidian' deleted and 'count' variable renamed as 'count_'

2023-01-16 16:09 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score

2023-01-16 16:09 UTC, closed without merging