Add a new type of tank w.r.t. #289
Yao-class-cpp-studio/battle_game pull request #352
Opened 2023-01-14 10:57 UTC by zhqwqwq

增加一种新坦克：【shadow tank】。其大招为召唤一个影子坦克【shadow】（为尽量维持游戏平衡（如果有？），该大招CD较长，为30s）。

为此，另增加一种新坦克【shadow】。其特征为：

- 不添加到selectable_units中
- 不受玩家控制，不可移动
- 可被攻击。
- 每5s向敌方坦克发射一个【rocket】子弹（可自动定位）。
- 可同时存在多个【shadow】坦克

另，对rocket.cpp进行了些许修改，使得【shadow】坦克发射的导弹不会攻击到己方坦克（包括【shadow tank】及其召唤出的其他【shadow】坦克）。

2023-01-14 11:42 UTC, zhqwqwq commented
游戏截图：
![](https://cdn.luogu.com.cn/upload/image_hosting/z24g7hvs.png)

2023-01-14 11:42 UTC, zhqwqwq commented
![](https://cdn.luogu.com.cn/upload/image_hosting/z24g7hvs.png)

2023-01-14 11:42 UTC, zhqwqwq commented
游戏截图：

![](https://cdn.luogu.com.cn/upload/image_hosting/z24g7hvs.png)

2023-01-14 11:44 UTC, zhqwqwq commented
[Click here](https://cdn.luogu.com.cn/upload/image_hosting/z24g7hvs.png)

2023-01-14 16:12 UTC, qinchuanhui requested changes
Plz re-organize ur code ( folder `enc_temp_folder` should not be included and pushed)

2023-01-15 09:57 UTC, qinchuanhui requested changes
Others LGTM!
But this branch should not be directly merged because it changed `tiny_tank.h`

2023-01-15 09:57 UTC, qinchuanhui commented on src/battle_game/core/units/shadow_tank_zhq.h
> +  uint32_t shadow_count_down{1800};
use `shadow_count_down_`

2023-01-15 09:57 UTC, qinchuanhui commented on src/battle_game/core/units/shadow_zhq.h
> +  uint32_t isHidden{0};
naming `is_hidden_`

2023-01-15 09:57 UTC, qinchuanhui commented on src/battle_game/core/units/rush_tank_zhq.h
> +  int rush_count_down;
naming problem

2023-01-15 09:57 UTC, qinchuanhui commented on src/battle_game/core/units/shadow_tank_zhq.h
> +  void Call_Shadow_Click();
Naming: `CallShadow`

2023-01-16 10:35 UTC, qinchuanhui approved these changes
OK，you can get the corresponding score

2023-01-16 10:35 UTC, closed without merging