Rush Tank
Yao-class-cpp-studio/battle_game pull request #353
Opened 2023-01-14 11:39 UTC by zhqwqwq

增加了一种新的坦克【Rush Tank】。其skill为增加移动速度，持续时间三秒。

2023-01-14 16:14 UTC, qinchuanhui requested changes
The same problem as #352 , plz re-organize ur code first

2023-01-16 11:03 UTC, qinchuanhui requested changes

2023-01-16 11:03 UTC, qinchuanhui commented on src/battle_game/core/units/shadow_tank_zhq.h
> +  ;
what‘s this

2023-01-16 11:03 UTC, qinchuanhui commented on src/battle_game/core/units/rush_tank_zhq.cpp
> +}  // namespace
seems u don't use these? maybe just delete them

2023-01-16 11:03 UTC, qinchuanhui commented on src/battle_game/core/units/rush_tank_zhq.h
> +  int time_stamp;
`time_stamp_`

2023-01-16 11:17 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score

2023-01-16 11:17 UTC, closed without merging

2023-01-16 11:54 UTC, zhqwqwq commented
This PR is for issue #334