All works
Yao-class-cpp-studio/battle_game pull request #380
Opened 2023-01-15 02:27 UTC by jiayu-Liu0407

My tank:LjyTank
My issue:
#178 LaserTank:Add a new skill "Destroy",which can use by press 'E' while left botton of mouse not being presssed.
#379 CollisionTank:Build the basis of collision tank,concluding damage and move system(moving system is improved by zhangkaixin)

2023-01-15 03:05 UTC, jiayu-Liu0407 commented
#379 Collision Tank:modify the damage system,damage now is 5*speed and 20*speed.when it is faster,damage will increase.

2023-01-15 03:30 UTC, jiayu-Liu0407 reviewed
#178 Add bullet laser

2023-01-15 15:35 UTC, qinchuanhui requested changes

2023-01-15 15:35 UTC, qinchuanhui commented on src/battle_game/core/bullets/laser.h
> +  int LightIndex_;
Function naming: `UpdateColor`, `GetWidth` (and I don't know what does 'width' mean, similar to other function names)
Private variables naming: `light_index_`, `combo_time_`

2023-01-15 15:35 UTC, qinchuanhui commented on src/battle_game/core/units/collision_tank.cpp
> +        auto cos_theta = std::cos(theta);
Inherit from `Tank` class if u don't change these functions

2023-01-15 15:35 UTC, qinchuanhui commented on src/battle_game/core/units/laser_tank.cpp
> +      turret_vertices.push_back(
The same, just inherit `Tank` class

2023-01-15 15:35 UTC, qinchuanhui commented on src/battle_game/core/units/ljy_tank.cpp
> +        theta *= glm::pi<float>() * 2.0f;
The same issue.

2023-01-15 15:35 UTC, qinchuanhui commented on src/battle_game/core/units/laser_tank.h
> +  uint32_t isDestroy = 0;
Naming issue

2023-01-15 15:35 UTC, qinchuanhui commented on src/battle_game/core/units/collision_tank.h
> +  std::map<uint32_t, bool> alreadyhit;
Naming issue

2023-01-16 13:50 UTC, qinchuanhui approved these changes
OK, u can get the corresponding score

2023-01-16 13:50 UTC, closed without merging