[New Unit] Heal Tank & [New Bullet] Inhale Bullet
Yao-class-cpp-studio/battle_game pull request #399
Opened 2023-01-15 09:24 UTC by jk21lcl

加入新单位：治疗坦克（heal tank）
特点：初始血量100，初始最大血量150，每0.8s回复1点血量，每15s在保持血量百分比不变的情况下将血量上限加10。
普通攻击方式：向前方40度范围内发射5颗伤害为6的子弹，攻击间隔1s。
E技能（inhale）：在5s内攻击间隔缩短至0.5s，向前方50度范围内发射9颗伤害为2的子弹，在这段时间内，每当有一颗子弹打中敌人时自身回复2点血量，技能冷却时间15s。
Q技能（refresh）：恢复至满血，冷却时间45s。

加入新子弹：吸血子弹（inhale bullet）
特点：打中敌方时可以让子弹发出者回复与子弹攻击力相同的血量

2023-01-15 09:49 UTC, qinchuanhui requested changes

2023-01-15 09:49 UTC, qinchuanhui commented on src/battle_game/core/units/heal_tank.h
> +  bool IsInhale() const;
Why set it as public, do you use it out of this class.

2023-01-15 09:53 UTC, jk21lcl commented on src/battle_game/core/units/heal_tank.h
> +  bool IsInhale() const;
我看unit.h和tiny_tank.h把它们都放在public里了，所以就放在public里了。
可能万一以后还要实现什么别的特性的话，会在这个类外面用到这些函数

2023-01-15 12:36 UTC, jk21lcl commented on src/battle_game/core/units/heal_tank.h
> +  bool IsInhale() const;
已修改

2023-01-16 09:57 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score

2023-01-16 09:57 UTC, closed without merging