Update README.md
Yao-class-cpp-studio/battle_game pull request #43
Opened 2023-01-04 05:02 UTC by zq-chen22

Just some nonsense in readme

2023-01-14 12:59 UTC, zq-chen22 commented
Add a new tank named by swift tank, which has three features.
Firstly, it rotates and moves faster.
Secondly, it have a "flesh": When you type in ‘F’ for the first time, you can flesh forward.
Thirdly, it will charge for a quintiple hit (五倍伤害的重击） every 6 seconds.

2023-01-16 10:41 UTC, qinchuanhui requested changes
Others LGTM

2023-01-16 10:41 UTC, qinchuanhui commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "units/swift_tank.h" "units/swift_tank.cpp")
Don't do this change

2023-01-16 10:41 UTC, qinchuanhui commented on README.md
> +经过一个学期的学习，我们已经一起学习了许多编程知识，大家的编程技能想必也有了显著的提高(doge)。
Undo this change

2023-01-16 12:15 UTC, zq-chen22 commented
Task 4 
1.help to make firebullet (done with 苏钰乐）
2.add a 'f' flesh (applied for swift tank)

2023-01-16 15:08 UTC, qinchuanhui approved these changes
LGTM, you can get the corresponding score

2023-01-16 15:10 UTC, qinchuanhui commented
> Task 4 1.help to make firebullet (done with 苏钰乐） 2.add a 'f' flesh (applied for swift tank)

seems this task haven't be done in this PR

2023-01-16 15:12 UTC, closed without merging