Draft (For subtask 1)
Yao-class-cpp-studio/battle_game pull request #48
Opened 2023-01-04 06:58 UTC by kx-zhang22

2023-01-04 12:19 UTC, kx-zhang22 commented
1

2023-01-13 05:31 UTC, kx-zhang22 commented
不需要merge到主仓库（：

2023-01-13 05:39 UTC, kx-zhang22 commented
不需要 merge 到主仓库，主要实现的功能：
1. 新的障碍物 swamp
2. 自定义坦克 kx_Tank（大部分和tiny_tank）相同
3. 自定义子弹 colorful_ball（发射时带偏转角度并且会炫彩的cannon_ball）
4. 自定义子弹 laser 和使用它的坦克 laser_tank（合作完成的issue的早期成品一起push上去了）
5. 自定义坦克 machine_tank（见issue268）

2023-01-13 15:05 UTC, LazyJazz requested changes

2023-01-13 15:05 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +add_library(${lib_name} units/Kirima_Kokona.h units/Kirima_Kokona.cpp   "bullets/laser.h" "bullets/laser.cpp" "units/laser_tank.h" "units/laser_tank.cpp" "units/machine_tank.cpp" "units/machine_tank.
Delete this.

2023-01-13 15:05 UTC, LazyJazz commented on src/battle_game/core/bullets/colorful_ball.cpp
> +void ColorfulBall::update_color(float &a) {
BigCamelCase

2023-01-13 15:05 UTC, LazyJazz commented on src/battle_game/core/bullets/laser.cpp
> +void Laser::update_color(float &a) {
BigCamelCase

2023-01-13 15:05 UTC, LazyJazz commented on src/battle_game/core/units/Kirima_Kokona.h
> +  bool is_stuck_by_swamp{false};
lower_case_ ending with an underscore

2023-01-13 15:05 UTC, LazyJazz commented on src/battle_game/core/units/tiny_tank.h
> +  bool is_stuck_by_swamp{false};
lower_case_ ending with an underscore

2023-01-13 15:05 UTC, LazyJazz commented on src/battle_game/core/units/machine_tank.cpp
> +}
inherit from unit::Tank if you are using the very same function.

2023-01-14 07:41 UTC, kx-zhang22 commented
Adjust the non-standard code above.

2023-01-15 03:31 UTC, kx-zhang22 commented
Adding regeneration and a new moving system to the collision tank in #379

2023-01-16 04:43 UTC, closed without merging