[Utility] Support online multi-player mode
Yao-class-cpp-studio/battle_game pull request #500
Opened 2023-01-23 14:58 UTC by ljc1301

In my implementation, the transmitted information is the users' input data, and all the computations are distributed to the clients.

You can start a server in the app window, or use
```shell
./battlegame --server [<port>]
```
where the default port is 8088.

Currently I've **only** tested the situation where **one player is connected to localhost and the server is run in the command line only**. Because it was for the first time that I wrote asynchronous program using multithread, I think it must contains many bugs, ~~and the code is just like a pile of :poop:~~ (so you are welcomed to rewrite the TCP parts). It seems that **the servers and clients sometimes crash**.

Something we can do later:
- [ ] Test and debug thoroughly;
- [ ] Document;
- [ ] Capture user's input in the ImGui window;
- [ ] Support both IPv4 and IPv6;
- [ ] Pure server with less dependencies (i.e. we can build a server without Vulkan and etc.);
- [ ] Any other utilities.

2023-01-25 10:21 UTC, sshockwave commented
我讲讲我的理解看有没有问题：

1. 客户端每个tick `CaptureInput`之后计入`input_data_`
2. 客户端每个tick发送一次`input_data_`
3. 服务端对每个client都循环接收`input_data_`
4. 服务端每个tick读一次client的`input_data_`并broadcast
5. 客户端收到broadcast的时候加进`input_data_queue_`
6. 每个`UpdateDrawCommands()` flush一次queue，然后调用`Update()`

这个实现在当前框架中非常简单直接！Thanks for your great work!

当然，这种实现的主要缺点是对延迟和丢包率要求极高，延迟或丢包会导致input queue不同步，不同客户端渲染不一致。不过在局域网内跑都没问题，之后我们再慢慢整。

2023-01-25 10:25 UTC, sshockwave requested changes

2023-01-25 10:25 UTC, sshockwave commented on src/battle_game/app/app.h
> +  std::queue<std::vector<MessageInputData>> input_data_queue_;
这里的`input_data_queue_`因为会被两个线程同时访问，需要加`std::mutex`。类似的还有`input_data_`。不过`write_messages_`应该不用，因为只有`io_context`进行单线程访问。

2023-01-25 10:25 UTC, sshockwave commented on src/battle_game/app/app.cpp
> +           (input_data_synced_ || !input_data_queue_.empty())) {
我没有太明白`input_data_synced_`的作用，是不是遗留的变量？

2023-01-25 12:56 UTC, ljc1301 commented on src/battle_game/app/app.cpp
> +           (input_data_synced_ || !input_data_queue_.empty())) {
确实是遗留的变量，现在已经删了。

2023-01-25 14:51 UTC, ljc1301 commented on src/battle_game/app/app.h
> +  std::queue<std::vector<MessageInputData>> input_data_queue_;
看起来问题还有在另一个线程中调用`app_->Start()`与`app_->Stop()`之类的:sob:我有空多改改

2023-01-28 14:52 UTC, ljc1301 commented on src/battle_game/app/app.h
> +  std::queue<std::vector<MessageInputData>> input_data_queue_;
现在应该改好了。

2023-01-28 15:02 UTC, ljc1301 commented on src/battle_game/app/client.cpp
> +}
我不太确定直接这样写安不安全（

2023-01-28 15:02 UTC, ljc1301 commented on src/battle_game/app/server.cpp
> +}
这里也是

2023-01-28 15:04 UTC, ljc1301 commented on src/battle_game/app/server.cpp
> +}
这里也是

2023-01-28 15:05 UTC, ljc1301 commented on src/battle_game/app/server.cpp
> +  }
这里也是

2023-01-28 15:05 UTC, ljc1301 commented on src/battle_game/app/server.cpp
> +}
这里也是

2023-01-28 15:09 UTC, ljc1301 commented on src/battle_game/app/server.cpp
> +                           (long long)std::roundl(1e9 * kSecondPerTick)));
这里（以及client.cpp类似的地方）应该有更好的写法（

2025-06-21 14:36 UTC, closed without merging