Simple Life Bar Implementation
Yao-class-cpp-studio/battle_game pull request #62
Opened 2023-01-04 15:30 UTC by unprintable123

添加了生命条并与原来的units兼容且同生命周期。
可以修改length，offset，color的设置。
虚继承大概只能自己再开一个Lifebar了然后hide原来的了。。。

2023-01-04 16:13 UTC, unprintable123 commented
添加了血量渐变的效果

2023-01-05 08:03 UTC, LazyJazz commented on src/battle_game/core/unit.h
> +      lifebar_ = new LifeBar(game_core_, id_);
We do not suggest using “new” in a formal project, could be unsafe.
Use smart pointers instead.

2023-01-05 08:04 UTC, LazyJazz commented
I think you can integrate this feature into Unit class. It's not necessary to make it an individual object.

2023-01-05 08:07 UTC, LazyJazz commented
After all, you've done a great job, and it would be better if you upload some screenshots of your work.

2023-01-05 09:02 UTC, unprintable123 commented
把lifebar改进去了（但设置不敢放出来，太乱了）
![image](https://user-images.githubusercontent.com/113123461/210741660-8381bf91-1c8c-4c71-81b5-de92393cb83d.png)

2023-01-05 14:34 UTC, LazyJazz requested changes

2023-01-05 14:34 UTC, LazyJazz commented on src/battle_game/core/unit.h
> +  glm::vec4 fadeout_color_{};
I mean, you can just put them into unit class. Or there's something else you were worried about.

2023-01-05 14:52 UTC, unprintable123 commented
改好了，之后觉得这些设置太乱了不负责（）

2023-01-06 14:05 UTC, merged