Unit & Bullet: Missile tank
Yao-class-cpp-studio/battle_game pull request #83
Opened 2023-01-05 14:17 UTC by unprintable123

添加了追踪导弹（以及测试用坦克）
也许之后会补一下导弹外观？

2023-01-05 14:21 UTC, LazyJazz submitted a review, later dismissed
Nice and clean. LGTM!

2023-01-07 15:39 UTC, LazyJazz requested changes

2023-01-07 15:39 UTC, LazyJazz commented on src/battle_game/core/units/missile_tank.cpp
> +}
Inherit from unit::Tank if you are using the very same code.

2023-01-07 15:39 UTC, LazyJazz commented on src/battle_game/core/units/missile_tank.cpp
> +}
These too.

2023-01-07 16:30 UTC, unprintable123 commented
改好了

2023-01-08 04:46 UTC, LazyJazz approved these changes
LGTM!

2023-01-08 04:46 UTC, merged