[Utility] buff API and Display
Yao-class-cpp-studio/battle_game pull request #97
Opened 2023-01-06 07:35 UTC by Whaooooo

在左上角血量下方显示buff与持续时间；
在 game_core.h中提供PushEventBuffUnit函数用于给指定unit(的player)施加buff；
在 player.h 中提供 GetBuffLayer 函数，它会返回指定BuffID对应Buff的层数；
在 player.h 中提供 GetBuffTime 函数，它会返回指定BuffID对应Buff指定层数的剩余时间；
请在 player.cpp 的 Player() 中添加你的Buff名（名字不太重要，清晰可区分就行）
同时请设定有关你Buff的四个属性:
1)Time_：一次Buff维持多少时间(以秒为单位；如果是无穷时长buff，填1.0即可)
2)IsSupportManyLayer_：此Buff是否允许多层叠加(true即表示可叠加)，目前只实现了每层buff独立的倒计时
3)IsInfiniteTime_：此Buff是否为永久Buff(true即表示永久，在unit活着的时候Buff永远不消失)
4)RemoveWhenDie_：当unit重生时去除多少层Buff(<0则全部去除，0则不去除，x>0则去除x层Buff)
请给自己的Buff选择一个int类型的BuffID，避免重复，用于函数调用

目前多层Buff会分成若干行分别显示；
请在 app.cpp 里完成你的Buff的显示信息：
1)对于非永久Buff，将"BuffName: %.xf ......"加入 BuffDisplay[] 以显示Buff剩余时间
2)对于永久Buff，文本格式随意
同时请将BuffID加入BuffID[]
Buff的图片显示等高阶功能目前没有任何进展()

目前已完成一个名为stunning的单层非永久DeBuff作为参考，此Buff持续1.5秒，在此期间player的全部操作会被无视，已设定为Player初始化时自带stunning效果。[
![1672990484535](https://user-images.githubusercontent.com/108567062/210952820-6fe70cf8-00e8-4e95-b946-8db469f979a3.jpg)
](url)[
![1672990502224](https://user-images.githubusercontent.com/108567062/210952861-101fb924-425f-4eb8-8885-ddffa04780a8.jpg)
](url)

2023-01-07 13:54 UTC, Whaooooo commented
Waiting for Code owner review [
![A~WCTNJ8K7O9RY 4BV%TPHU](https://user-images.githubusercontent.com/108567062/211154275-1be9ef5e-7b19-4afe-83da-2df64476c9a1.jpg)
](url)

2023-01-07 15:47 UTC, LazyJazz requested changes

2023-01-07 15:47 UTC, LazyJazz commented on src/battle_game/app/app.cpp
> +int BuffID[] = {0};
```suggestion
namespace {
  const int TotalBuffNumber = 1;
  const char *BuffDisplay[] = {"Stunning: %.1f"};
  int BuffID[] = {0};
}
```

variable names should be in lower_case

2023-01-07 15:47 UTC, LazyJazz commented on src/battle_game/core/player.h
> +};
put these codes into new files: buff.h and buff.cpp
make variables private
private variable names should be in lower_case_ endding with an underscore.

2023-01-07 15:47 UTC, LazyJazz commented on src/battle_game/core/player.h
> +  std::vector<battle_game::Buff> BuffList_;
lower_case_

2023-01-07 17:05 UTC, Whaooooo commented
Fixed. 
Thx

2023-01-08 01:36 UTC, Whaooooo commented
There's some bug... wait a minute

2023-01-08 01:55 UTC, Whaooooo commented
Now all down

2023-01-09 11:15 UTC, LazyJazz requested changes
LGTM! Just fix the nit. Call me in wechat if you want to merge your contribution into the main branch.

2023-01-09 11:15 UTC, LazyJazz commented on src/battle_game/core/CMakeLists.txt
> +target_sources(${lib_name} PRIVATE ${source_files} "buff.h" "buff.cpp")
You don't need to add this!

2023-01-12 14:42 UTC, LazyJazz approved these changes
LGTM!

2023-01-15 10:48 UTC, closed without merging