Add a new unit: Zibeng Dog
Yao-class-cpp-studio/battle_game pull request #98
Opened 2023-01-06 07:41 UTC by jinchen-jiang

2023-01-06 07:46 UTC, jinchen-jiang commented
滋崩狗与普通坦克相比，舍弃了重装甲，有着更好的机动性（更高的移速），但生命值只有50。它使用一种全新的子弹：流汗黄豆进行攻击，子弹与加农炮弹相比，有着更高的飞行速度，但作为代价，它的子弹杀伤力只有加农炮弹的80%。

2023-01-06 11:13 UTC, jinchen-jiang commented
为了更贴合滋崩的伤害逻辑，我对【滋崩狗】的伤害逻辑进行了更新：
每次射击，会产生【流汗黄豆·滋】，由一串【流汗黄豆】构成，每颗造成少量伤害；
【流汗黄豆·滋】结束时，会释放一颗【流汗黄豆·崩】，造成【加农炮弹】80%的伤害。

2023-01-07 15:49 UTC, LazyJazz requested changes
LGTM! Only some nits.

2023-01-07 15:49 UTC, LazyJazz commented on CMakeSettings.json
> +}
Delete this file

2023-01-07 15:49 UTC, LazyJazz commented on JJC_README.md
> +# El psy ~~congari~~ congroo
Delete this, too.

2023-01-08 02:34 UTC, closed without merging